// library-frontend/src/components/UserForm/UserForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { userService } from '../../services/userService';

const UserForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({
    email: '',
    passwordHash: '',
    firstName: '',
    lastName: '',
    phone: '',
    address: '',
    role: 'READER',
    isActive: true
  });

  useEffect(() => {
    if (isEdit) {
      fetchUser();
    }
  }, [id]);

  const fetchUser = async () => {
    try {
      setLoading(true);
      const user = await userService.getById(Number(id));
      setFormData({
        email: user.email,
        passwordHash: '',
        firstName: user.firstName,
        lastName: user.lastName,
        phone: user.phone || '',
        address: user.address || '',
        role: user.role,
        isActive: user.isActive
      });
    } catch (err) {
      setError('Ошибка загрузки пользователя');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setLoading(true);
      if (isEdit) {
        await userService.update(Number(id), formData);
      } else {
        await userService.create(formData);
      }
      navigate('/users');
    } catch (err) {
      setError('Ошибка сохранения');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value
    }));
  };

  if (loading && isEdit) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="container mt-4">
      <div className="card">
        <div className="card-header">
          <h3>{isEdit ? '✏️ Редактирование пользователя' : '➕ Новый пользователь'}</h3>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Email *</label>
                <input
                  type="email"
                  className="form-control"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  required
                />
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">{isEdit ? 'Новый пароль' : 'Пароль *'}</label>
                <input
                  type="password"
                  className="form-control"
                  name="passwordHash"
                  value={formData.passwordHash}
                  onChange={handleChange}
                  required={!isEdit}
                  placeholder={isEdit ? 'Оставьте пустым, чтобы не менять' : ''}
                />
              </div>
            </div>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Имя *</label>
                <input
                  type="text"
                  className="form-control"
                  name="firstName"
                  value={formData.firstName}
                  onChange={handleChange}
                  required
                />
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">Фамилия *</label>
                <input
                  type="text"
                  className="form-control"
                  name="lastName"
                  value={formData.lastName}
                  onChange={handleChange}
                  required
                />
              </div>
            </div>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Телефон</label>
                <input
                  type="text"
                  className="form-control"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                />
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">Роль</label>
                <select
                  className="form-select"
                  name="role"
                  value={formData.role}
                  onChange={handleChange}
                >
                  <option value="READER">Читатель</option>
                  <option value="ADMIN">Администратор</option>
                </select>
              </div>
            </div>
            <div className="mb-3">
              <label className="form-label">Адрес</label>
              <input
                type="text"
                className="form-control"
                name="address"
                value={formData.address}
                onChange={handleChange}
              />
            </div>
            {isEdit && (
              <div className="mb-3 form-check">
                <input
                  type="checkbox"
                  className="form-check-input"
                  name="isActive"
                  checked={formData.isActive}
                  onChange={handleChange}
                />
                <label className="form-check-label">Активен</label>
              </div>
            )}
            <div className="d-flex gap-2 mt-3">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Сохранение...' : 'Сохранить'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/users')}>
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default UserForm;

// angular-frontend/src/app/components/user-form/user-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { UserService } from '../../services/user.service';
import { UserCreateDTO, UserUpdateDTO } from '../../models/user.model';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.css']
})
export class UserFormComponent implements OnInit {
  isEdit = false;
  id?: number;
  loading = false;
  error = '';

  formData: UserCreateDTO & UserUpdateDTO = {
    email: '',
    passwordHash: '',
    firstName: '',
    lastName: '',
    phone: '',
    address: '',
    role: 'READER',
    isActive: true
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
    this.isEdit = !!this.id;
    if (this.isEdit) {
      this.fetchUser();
    }
  }

  fetchUser(): void {
    this.loading = true;
    this.userService.getById(this.id!).subscribe({
      next: (user) => {
        this.formData = {
          email: user.email,
          passwordHash: '',
          firstName: user.firstName,
          lastName: user.lastName,
          phone: user.phone || '',
          address: user.address || '',
          role: user.role,
          isActive: user.isActive
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки пользователя';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    const request = this.isEdit
      ? this.userService.update(this.id!, this.formData)
      : this.userService.create(this.formData as UserCreateDTO);
    request.subscribe({
      next: () => {
        this.router.navigate(['/users']);
      },
      error: (err) => {
        this.error = 'Ошибка сохранения';
        console.error(err);
        this.loading = false;
      }
    });
  }
}
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h3>{{ isEdit ? '✏️ Редактирование пользователя' : '➕ Новый пользователь' }}</h3>
    </div>
    <div class="card-body">
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <form (ngSubmit)="onSubmit()">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Email *</label>
            <input type="email" class="form-control" [(ngModel)]="formData.email" name="email" required>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">{{ isEdit ? 'Новый пароль' : 'Пароль *' }}</label>
            <input type="password" class="form-control" [(ngModel)]="formData.passwordHash" name="passwordHash" [required]="!isEdit" [placeholder]="isEdit ? 'Оставьте пустым, чтобы не менять' : ''">
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Имя *</label>
            <input type="text" class="form-control" [(ngModel)]="formData.firstName" name="firstName" required>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Фамилия *</label>
            <input type="text" class="form-control" [(ngModel)]="formData.lastName" name="lastName" required>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Телефон</label>
            <input type="text" class="form-control" [(ngModel)]="formData.phone" name="phone">
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Роль</label>
            <select class="form-select" [(ngModel)]="formData.role" name="role">
              <option value="READER">Читатель</option>
              <option value="ADMIN">Администратор</option>
            </select>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Адрес</label>
          <input type="text" class="form-control" [(ngModel)]="formData.address" name="address">
        </div>

        <div *ngIf="isEdit" class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" [(ngModel)]="formData.isActive" name="isActive">
          <label class="form-check-label">Активен</label>
        </div>

        <div class="d-flex gap-2 mt-3">
          <button type="submit" class="btn btn-primary" [disabled]="loading">{{ loading ? 'Сохранение...' : 'Сохранить' }}</button>
          <button type="button" class="btn btn-secondary" routerLink="/users">Отмена</button>
        </div>
      </form>
    </div>
  </div>
</div>
