// angular-frontend/src/app/components/genre-form/genre-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { GenreService } from '../../services/genre.service';
import { GenreCreateDTO, GenreUpdateDTO } from '../../models/genre.model';

@Component({
  selector: 'app-genre-form',
  templateUrl: './genre-form.component.html',
  styleUrls: ['./genre-form.component.css']
})
export class GenreFormComponent implements OnInit {
  isEdit = false;
  id?: number;
  loading = false;
  error = '';

  formData: GenreCreateDTO & GenreUpdateDTO = {
    name: '',
    description: ''
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private genreService: GenreService
  ) {}

  ngOnInit(): void {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
    this.isEdit = !!this.id;
    if (this.isEdit) {
      this.fetchGenre();
    }
  }

  fetchGenre(): void {
    this.loading = true;
    this.genreService.getById(this.id!).subscribe({
      next: (genre) => {
        this.formData = {
          name: genre.name,
          description: genre.description || ''
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки жанра';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    const request = this.isEdit
      ? this.genreService.update(this.id!, this.formData)
      : this.genreService.create(this.formData as GenreCreateDTO);
    request.subscribe({
      next: () => {
        this.router.navigate(['/genres']);
      },
      error: (err) => {
        this.error = 'Ошибка сохранения';
        console.error(err);
        this.loading = false;
      }
    });
  }
}
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h3>{{ isEdit ? '✏️ Редактирование жанра' : '➕ Новый жанр' }}</h3>
    </div>
    <div class="card-body">
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <form (ngSubmit)="onSubmit()">
        <div class="mb-3">
          <label class="form-label">Название *</label>
          <input type="text" class="form-control" [(ngModel)]="formData.name" name="name" required>
        </div>

        <div class="mb-3">
          <label class="form-label">Описание</label>
          <textarea class="form-control" [(ngModel)]="formData.description" name="description" rows="3"></textarea>
        </div>

        <div class="d-flex gap-2 mt-3">
          <button type="submit" class="btn btn-primary" [disabled]="loading">{{ loading ? 'Сохранение...' : 'Сохранить' }}</button>
          <button type="button" class="btn btn-secondary" routerLink="/genres">Отмена</button>
        </div>
      </form>
    </div>
  </div>
</div>

// library-frontend/src/components/GenreForm/GenreForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { genreService } from '../../services/genreService';

interface GenreFormData {
  name: string;
  description: string;
}

const GenreForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState<GenreFormData>({
    name: '',
    description: ''
  });

  useEffect(() => {
    if (isEdit) {
      fetchGenre();
    }
  }, [id]);

  const fetchGenre = async () => {
    try {
      setLoading(true);
      const genre = await genreService.getById(Number(id));
      setFormData({
        name: genre.name,
        description: genre.description || ''
      });
    } catch (err) {
      setError('Ошибка загрузки жанра');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setLoading(true);
      if (isEdit) {
        await genreService.update(Number(id), formData);
      } else {
        await genreService.create(formData);
      }
      navigate('/genres');
    } catch (err) {
      setError('Ошибка сохранения');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev: GenreFormData) => ({ ...prev, [name]: value }));
  };

  if (loading && isEdit) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="container mt-4">
      <div className="card">
        <div className="card-header">
          <h3>{isEdit ? '✏️ Редактирование жанра' : '➕ Новый жанр'}</h3>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          <form onSubmit={handleSubmit}>
            <div className="mb-3">
              <label className="form-label">Название *</label>
              <input
                type="text"
                className="form-control"
                name="name"
                value={formData.name}
                onChange={handleChange}
                required
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Описание</label>
              <textarea
                className="form-control"
                name="description"
                value={formData.description}
                onChange={handleChange}
                rows={3}
              />
            </div>
            <div className="d-flex gap-2 mt-3">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Сохранение...' : 'Сохранить'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/genres')}>
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default GenreForm;
