// library-frontend/src/components/AuthorForm/AuthorForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { authorService } from '../../services/authorService';

interface AuthorFormData {
  firstName: string;
  lastName: string;
  birthDate: string;
  biography: string;
}

const AuthorForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState<AuthorFormData>({
    firstName: '',
    lastName: '',
    birthDate: '',
    biography: ''
  });

  useEffect(() => {
    if (isEdit) {
      fetchAuthor();
    }
  }, [id]);

  const fetchAuthor = async () => {
    try {
      setLoading(true);
      const author = await authorService.getById(Number(id));
      setFormData({
        firstName: author.firstName,
        lastName: author.lastName,
        birthDate: author.birthDate || '',
        biography: author.biography || ''
      });
    } catch (err) {
      setError('Ошибка загрузки автора');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setLoading(true);
      if (isEdit) {
        await authorService.update(Number(id), formData);
      } else {
        await authorService.create(formData);
      }
      navigate('/authors');
    } catch (err) {
      setError('Ошибка сохранения');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev: AuthorFormData) => ({ ...prev, [name]: value }));
  };

  if (loading && isEdit) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="container mt-4">
      <div className="card">
        <div className="card-header">
          <h3>{isEdit ? '✏️ Редактирование автора' : '➕ Новый автор'}</h3>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Имя *</label>
                <input
                  type="text"
                  className="form-control"
                  name="firstName"
                  value={formData.firstName}
                  onChange={handleChange}
                  required
                />
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">Фамилия *</label>
                <input
                  type="text"
                  className="form-control"
                  name="lastName"
                  value={formData.lastName}
                  onChange={handleChange}
                  required
                />
              </div>
            </div>
            <div className="mb-3">
              <label className="form-label">Дата рождения</label>
              <input
                type="date"
                className="form-control"
                name="birthDate"
                value={formData.birthDate}
                onChange={handleChange}
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Биография</label>
              <textarea
                className="form-control"
                name="biography"
                value={formData.biography}
                onChange={handleChange}
                rows={4}
              />
            </div>
            <div className="d-flex gap-2 mt-3">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Сохранение...' : 'Сохранить'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/authors')}>
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default AuthorForm;

// angular-frontend/src/app/components/author-form/author-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthorService } from '../../services/author.service';
import { AuthorCreateDTO, AuthorUpdateDTO } from '../../models/author.model';

@Component({
  selector: 'app-author-form',
  templateUrl: './author-form.component.html',
  styleUrls: ['./author-form.component.css']
})
export class AuthorFormComponent implements OnInit {
  isEdit = false;
  id?: number;
  loading = false;
  error = '';

  formData: AuthorCreateDTO & AuthorUpdateDTO = {
    firstName: '',
    lastName: '',
    birthDate: '',
    biography: ''
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private authorService: AuthorService
  ) {}

  ngOnInit(): void {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
    this.isEdit = !!this.id;
    if (this.isEdit) {
      this.fetchAuthor();
    }
  }

  fetchAuthor(): void {
    this.loading = true;
    this.authorService.getById(this.id!).subscribe({
      next: (author) => {
        this.formData = {
          firstName: author.firstName,
          lastName: author.lastName,
          birthDate: author.birthDate || '',
          biography: author.biography || ''
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки автора';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    const request = this.isEdit
      ? this.authorService.update(this.id!, this.formData)
      : this.authorService.create(this.formData as AuthorCreateDTO);
    request.subscribe({
      next: () => {
        this.router.navigate(['/authors']);
      },
      error: (err) => {
        this.error = 'Ошибка сохранения';
        console.error(err);
        this.loading = false;
      }
    });
  }
}
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h3>{{ isEdit ? '✏️ Редактирование автора' : '➕ Новый автор' }}</h3>
    </div>
    <div class="card-body">
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <form (ngSubmit)="onSubmit()">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Имя *</label>
            <input type="text" class="form-control" [(ngModel)]="formData.firstName" name="firstName" required>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Фамилия *</label>
            <input type="text" class="form-control" [(ngModel)]="formData.lastName" name="lastName" required>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Дата рождения</label>
          <input type="date" class="form-control" [(ngModel)]="formData.birthDate" name="birthDate">
        </div>

        <div class="mb-3">
          <label class="form-label">Биография</label>
          <textarea class="form-control" [(ngModel)]="formData.biography" name="biography" rows="4"></textarea>
        </div>

        <div class="d-flex gap-2 mt-3">
          <button type="submit" class="btn btn-primary" [disabled]="loading">{{ loading ? 'Сохранение...' : 'Сохранить' }}</button>
          <button type="button" class="btn btn-secondary" routerLink="/authors">Отмена</button>
        </div>
      </form>
    </div>
  </div>
</div>
