// library-frontend/src/components/LoanList/LoanList.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { loanService } from '../../services/loanService';
import { Loan } from '../../models/loan.model';
import { PageResponse } from '../../models/pagination.model';

const LoanList: React.FC = () => {
  const navigate = useNavigate();
  const [loans, setLoans] = useState<Loan[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [totalElements, setTotalElements] = useState(0);

  useEffect(() => {
    fetchLoans();
  }, [page]);

  const fetchLoans = async () => {
    try {
      setLoading(true);
      const response: PageResponse<Loan> = await loanService.getAll({ page, size: 10 });
      setLoans(response.content);
      setTotalPages(response.totalPages);
      setTotalElements(response.totalElements);
      setError('');
    } catch (err: any) {
      setError('Ошибка загрузки данных: ' + (err.message || ''));
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('Вы уверены, что хотите удалить эту запись?')) {
      try {
        await loanService.delete(id);
        fetchLoans();
      } catch (err) {
        setError('Ошибка удаления');
        console.error(err);
      }
    }
  };

  const handleReturn = async (id: number) => {
    try {
      await loanService.returnBook(id);
      fetchLoans();
    } catch (err) {
      setError('Ошибка при возврате книги');
      console.error(err);
    }
  };

  const getStatusBadge = (status: string) => {
    const statusMap: { [key: string]: string } = {
      'ACTIVE': 'bg-success',
      'RETURNED': 'bg-secondary',
      'OVERDUE': 'bg-danger'
    };
    return `badge ${statusMap[status] || 'bg-info'}`;
  };

  if (loading) {
    return (
      <div className="d-flex justify-content-center mt-5">
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Загрузка...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h2>📖 Управление выдачами книг</h2>
        <div>
          <button 
            className="btn btn-primary me-2"
            onClick={() => navigate('/loans/new')}
          >
            ➕ Новая выдача
          </button>
          <span className="badge bg-primary">Всего: {totalElements}</span>
        </div>
      </div>

      {error && (
        <div className="alert alert-danger alert-dismissible fade show" role="alert">
          {error}
          <button type="button" className="btn-close" onClick={() => setError('')}></button>
        </div>
      )}

      <div className="table-responsive">
        <table className="table table-striped table-hover">
          <thead className="table-dark">
            <tr>
              <th>ID</th>
              <th>Книга</th>
              <th>Читатель</th>
              <th>Дата выдачи</th>
              <th>Срок возврата</th>
              <th>Статус</th>
              <th>Штраф</th>
              <th>Действия</th>
            </tr>
          </thead>
          <tbody>
            {loans.length === 0 ? (
              <tr>
                <td colSpan={8} className="text-center text-muted py-3">Нет данных</td>
              </tr>
            ) : (
              loans.map((loan) => (
                <tr key={loan.id}>
                  <td>{loan.id}</td>
                  <td>{loan.bookTitle || '—'}</td>
                  <td>{loan.userName || '—'}</td>
                  <td>{new Date(loan.loanDate).toLocaleDateString()}</td>
                  <td>{new Date(loan.dueDate).toLocaleDateString()}</td>
                  <td>
                    <span className={getStatusBadge(loan.status)}>
                      {loan.status}
                    </span>
                  </td>
                  <td>{(loan.fineAmount || 0).toFixed(2)}</td>
                  <td>
                    <button
                      className="btn btn-sm btn-info me-1"
                      onClick={() => navigate(`/loans/${loan.id}/edit`)}
                      title="Редактировать"
                    >
                      ✏️
                    </button>
                    {(loan.status === 'ACTIVE' || loan.status === 'OVERDUE') && (
                      <button
                        className="btn btn-sm btn-success me-1"
                        onClick={() => handleReturn(loan.id!)}
                        title="Вернуть книгу"
                      >
                        ↩️
                      </button>
                    )}
                    <button
                      className="btn btn-sm btn-danger"
                      onClick={() => handleDelete(loan.id!)}
                      title="Удалить запись"
                    >
                      🗑️
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {totalPages > 1 && (
        <nav className="mt-3">
          <ul className="pagination justify-content-center">
            <li className={`page-item ${page === 0 ? 'disabled' : ''}`}>
              <button className="page-link" onClick={() => setPage(page - 1)}>
                Назад
              </button>
            </li>
            {[...Array(Math.min(totalPages, 7))].map((_, i) => {
              let pageNum = i;
              if (totalPages > 7) {
                if (page < 3) pageNum = i;
                else if (page > totalPages - 4) pageNum = totalPages - 7 + i;
                else pageNum = page - 3 + i;
              }
              return (
                <li key={pageNum} className={`page-item ${page === pageNum ? 'active' : ''}`}>
                  <button className="page-link" onClick={() => setPage(pageNum)}>
                    {pageNum + 1}
                  </button>
                </li>
              );
            })}
            <li className={`page-item ${page >= totalPages - 1 ? 'disabled' : ''}`}>
              <button className="page-link" onClick={() => setPage(page + 1)}>
                Вперед
              </button>
            </li>
          </ul>
        </nav>
      )}
    </div>
  );
};

export default LoanList;

// angular-frontend/src/app/components/loan-list/loan-list.component.ts
import { Component, OnInit } from '@angular/core';
import { LoanService } from '../../services/loan.service';
import { Loan } from '../../models/loan.model';
import { PageResponse } from '../../models/pagination.model';

@Component({
  selector: 'app-loan-list',
  templateUrl: './loan-list.component.html',
  styleUrls: ['./loan-list.component.css']
})
export class LoanListComponent implements OnInit {
  loans: Loan[] = [];
  loading = true;
  error = '';
  page = 0;
  totalPages = 0;
  totalElements = 0;

  constructor(private loanService: LoanService) {}

  ngOnInit(): void {
    this.fetchLoans();
  }

  fetchLoans(): void {
    this.loading = true;
    this.loanService.getAll({ page: this.page, size: 10 }).subscribe({
      next: (response: PageResponse<Loan>) => {
        this.loans = response.content;
        this.totalPages = response.totalPages;
        this.totalElements = response.totalElements;
        this.error = '';
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки данных';
        console.error(err);
        this.loading = false;
      }
    });
  }

  deleteLoan(id: number): void {
    if (confirm('Вы уверены, что хотите удалить эту запись?')) {
      this.loanService.delete(id).subscribe({
        next: () => this.fetchLoans(),
        error: (err) => {
          this.error = 'Ошибка удаления';
          console.error(err);
        }
      });
    }
  }

  returnBook(id: number): void {
    this.loanService.returnBook(id).subscribe({
      next: () => this.fetchLoans(),
      error: (err) => {
        this.error = 'Ошибка при возврате книги';
        console.error(err);
      }
    });
  }

  getStatusBadge(status: string): string {
    const map: { [key: string]: string } = {
      'ACTIVE': 'bg-success',
      'RETURNED': 'bg-secondary',
      'OVERDUE': 'bg-danger'
    };
    return `badge ${map[status] || 'bg-info'}`;
  }

  changePage(page: number): void {
    this.page = page;
    this.fetchLoans();
  }

  getPageNumbers(): number[] {
    const pages: number[] = [];
    const total = Math.min(this.totalPages, 7);
    let start = 0;
    if (this.totalPages > 7) {
      if (this.page < 3) {
        start = 0;
      } else if (this.page > this.totalPages - 4) {
        start = this.totalPages - 7;
      } else {
        start = this.page - 3;
      }
    }
    for (let i = 0; i < total; i++) {
      pages.push(start + i);
    }
    return pages;
  }
}
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2>📖 Управление выдачами книг</h2>
    <div>
      <button class="btn btn-primary me-2" routerLink="/loans/new">➕ Новая выдача</button>
      <span class="badge bg-primary">Всего: {{ totalElements }}</span>
    </div>
  </div>

  <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

  <div *ngIf="loading" class="text-center mt-5">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Загрузка...</span>
    </div>
  </div>

  <div class="table-responsive" *ngIf="!loading">
    <table class="table table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>ID</th>
          <th>Книга</th>
          <th>Читатель</th>
          <th>Дата выдачи</th>
          <th>Срок возврата</th>
          <th>Статус</th>
          <th>Штраф</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngIf="loans.length === 0">
          <td colspan="8" class="text-center text-muted py-3">Нет данных</td>
        </tr>
        <tr *ngFor="let loan of loans">
          <td>{{ loan.id }}</td>
          <td>{{ loan.bookTitle || '—' }}</td>
          <td>{{ loan.userName || '—' }}</td>
          <td>{{ loan.loanDate | date:'dd.MM.yyyy' }}</td>
          <td>{{ loan.dueDate | date:'dd.MM.yyyy' }}</td>
          <td><span [class]="getStatusBadge(loan.status)">{{ loan.status }}</span></td>
          <td>{{ (loan.fineAmount || 0).toFixed(2) }}</td>
          <td>
            <button class="btn btn-sm btn-info me-1" [routerLink]="['/loans', loan.id, 'edit']">✏️</button>
            <button *ngIf="loan.status === 'ACTIVE' || loan.status === 'OVERDUE'" class="btn btn-sm btn-success me-1" (click)="returnBook(loan.id!)">↩️</button>
            <button class="btn btn-sm btn-danger" (click)="deleteLoan(loan.id!)">🗑️</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <nav *ngIf="totalPages > 1" class="mt-3">
    <ul class="pagination justify-content-center">
      <li class="page-item" [class.disabled]="page === 0">
        <button class="page-link" (click)="changePage(page - 1)">Назад</button>
      </li>
      <li class="page-item" *ngFor="let pageNum of getPageNumbers()" [class.active]="page === pageNum">
        <button class="page-link" (click)="changePage(pageNum)">{{ pageNum + 1 }}</button>
      </li>
      <li class="page-item" [class.disabled]="page >= totalPages - 1">
        <button class="page-link" (click)="changePage(page + 1)">Вперед</button>
      </li>
    </ul>
  </nav>
</div>
