// angular-frontend/src/app/components/publisher-form/publisher-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { PublisherService } from '../../services/publisher.service';
import { PublisherCreateDTO, PublisherUpdateDTO } from '../../models/publisher.model';

@Component({
  selector: 'app-publisher-form',
  templateUrl: './publisher-form.component.html',
  styleUrls: ['./publisher-form.component.css']
})
export class PublisherFormComponent implements OnInit {
  isEdit = false;
  id?: number;
  loading = false;
  error = '';

  formData: PublisherCreateDTO & PublisherUpdateDTO = {
    name: '',
    address: '',
    phone: '',
    email: '',
    website: ''
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private publisherService: PublisherService
  ) {}

  ngOnInit(): void {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
    this.isEdit = !!this.id;
    if (this.isEdit) {
      this.fetchPublisher();
    }
  }

  fetchPublisher(): void {
    this.loading = true;
    this.publisherService.getById(this.id!).subscribe({
      next: (publisher) => {
        this.formData = {
          name: publisher.name,
          address: publisher.address || '',
          phone: publisher.phone || '',
          email: publisher.email || '',
          website: publisher.website || ''
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки издателя';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    const request = this.isEdit
      ? this.publisherService.update(this.id!, this.formData)
      : this.publisherService.create(this.formData as PublisherCreateDTO);
    request.subscribe({
      next: () => {
        this.router.navigate(['/publishers']);
      },
      error: (err) => {
        this.error = 'Ошибка сохранения';
        console.error(err);
        this.loading = false;
      }
    });
  }
}
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h3>{{ isEdit ? '✏️ Редактирование издателя' : '➕ Новый издатель' }}</h3>
    </div>
    <div class="card-body">
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <form (ngSubmit)="onSubmit()">
        <div class="mb-3">
          <label class="form-label">Название *</label>
          <input type="text" class="form-control" [(ngModel)]="formData.name" name="name" required>
        </div>

        <div class="mb-3">
          <label class="form-label">Адрес</label>
          <input type="text" class="form-control" [(ngModel)]="formData.address" name="address">
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Телефон</label>
            <input type="text" class="form-control" [(ngModel)]="formData.phone" name="phone">
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Email</label>
            <input type="email" class="form-control" [(ngModel)]="formData.email" name="email">
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Веб-сайт</label>
          <input type="text" class="form-control" [(ngModel)]="formData.website" name="website">
        </div>

        <div class="d-flex gap-2 mt-3">
          <button type="submit" class="btn btn-primary" [disabled]="loading">{{ loading ? 'Сохранение...' : 'Сохранить' }}</button>
          <button type="button" class="btn btn-secondary" routerLink="/publishers">Отмена</button>
        </div>
      </form>
    </div>
  </div>
</div>

// library-frontend/src/components/PublisherForm/PublisherForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { publisherService } from '../../services/publisherService';

interface PublisherFormData {
  name: string;
  address: string;
  phone: string;
  email: string;
  website: string;
}

const PublisherForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState<PublisherFormData>({
    name: '',
    address: '',
    phone: '',
    email: '',
    website: ''
  });

  useEffect(() => {
    if (isEdit) {
      fetchPublisher();
    }
  }, [id]);

  const fetchPublisher = async () => {
    try {
      setLoading(true);
      const publisher = await publisherService.getById(Number(id));
      setFormData({
        name: publisher.name,
        address: publisher.address || '',
        phone: publisher.phone || '',
        email: publisher.email || '',
        website: publisher.website || ''
      });
    } catch (err) {
      setError('Ошибка загрузки издателя');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setLoading(true);
      if (isEdit) {
        await publisherService.update(Number(id), formData);
      } else {
        await publisherService.create(formData);
      }
      navigate('/publishers');
    } catch (err) {
      setError('Ошибка сохранения');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev: PublisherFormData) => ({ ...prev, [name]: value }));
  };

  if (loading && isEdit) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="container mt-4">
      <div className="card">
        <div className="card-header">
          <h3>{isEdit ? '✏️ Редактирование издателя' : '➕ Новый издатель'}</h3>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          <form onSubmit={handleSubmit}>
            <div className="mb-3">
              <label className="form-label">Название *</label>
              <input
                type="text"
                className="form-control"
                name="name"
                value={formData.name}
                onChange={handleChange}
                required
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Адрес</label>
              <input
                type="text"
                className="form-control"
                name="address"
                value={formData.address}
                onChange={handleChange}
              />
            </div>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Телефон</label>
                <input
                  type="text"
                  className="form-control"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                />
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">Email</label>
                <input
                  type="email"
                  className="form-control"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                />
              </div>
            </div>
            <div className="mb-3">
              <label className="form-label">Веб-сайт</label>
              <input
                type="text"
                className="form-control"
                name="website"
                value={formData.website}
                onChange={handleChange}
              />
            </div>
            <div className="d-flex gap-2 mt-3">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Сохранение...' : 'Сохранить'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/publishers')}>
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default PublisherForm;
