// library-frontend/src/components/LoanForm/LoanForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { loanService } from '../../services/loanService';
import { bookService } from '../../services/bookService';
import { userService } from '../../services/userService';

interface LoanFormData {
  bookId: number;
  userId: number;
  status: 'ACTIVE' | 'RETURNED' | 'OVERDUE';
  fineAmount: number;
}

const LoanForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [books, setBooks] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);

  const [formData, setFormData] = useState<LoanFormData>({
    bookId: 0,
    userId: 0,
    status: 'ACTIVE',
    fineAmount: 0
  });

  useEffect(() => {
    fetchBooksAndUsers();
    if (isEdit) {
      fetchLoan();
    }
  }, [id]);

  const fetchBooksAndUsers = async () => {
    try {
      const [booksRes, usersRes] = await Promise.all([
        bookService.getAll({ page: 0, size: 100 }),
        userService.getAll({ page: 0, size: 100 })
      ]);
      setBooks(booksRes.content);
      setUsers(usersRes.content);
    } catch (err) {
      setError('Ошибка загрузки данных');
      console.error(err);
    }
  };

  const fetchLoan = async () => {
    try {
      setLoading(true);
      const loan = await loanService.getById(Number(id));
      setFormData({
        bookId: loan.bookId,
        userId: loan.userId,
        status: loan.status,
        fineAmount: loan.fineAmount
      });
    } catch (err) {
      setError('Ошибка загрузки выдачи');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setLoading(true);
      if (isEdit) {
        await loanService.update(Number(id), formData);
      } else {
        await loanService.create(formData);
      }
      navigate('/loans');
    } catch (err) {
      setError('Ошибка сохранения');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement | HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev: LoanFormData) => ({
      ...prev,
      [name]: name === 'bookId' || name === 'userId' || name === 'fineAmount' 
        ? Number(value) 
        : value
    }));
  };

  if (loading && isEdit) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="container mt-4">
      <div className="card">
        <div className="card-header">
          <h3>{isEdit ? '✏️ Редактирование выдачи' : '➕ Новая выдача'}</h3>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Книга *</label>
                <select
                  className="form-select"
                  name="bookId"
                  value={formData.bookId}
                  onChange={handleChange}
                  required
                >
                  <option value={0}>Выберите книгу</option>
                  {books.map((book: any) => (
                    <option key={book.id} value={book.id}>
                      {book.title} (доступно: {book.availableCopies || 0})
                    </option>
                  ))}
                </select>
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">Пользователь *</label>
                <select
                  className="form-select"
                  name="userId"
                  value={formData.userId}
                  onChange={handleChange}
                  required
                >
                  <option value={0}>Выберите пользователя</option>
                  {users.map((user: any) => (
                    <option key={user.id} value={user.id}>
                      {user.fullName} ({user.email})
                    </option>
                  ))}
                </select>
              </div>
            </div>
            {isEdit && (
              <div className="row">
                <div className="col-md-6 mb-3">
                  <label className="form-label">Статус</label>
                  <select
                    className="form-select"
                    name="status"
                    value={formData.status}
                    onChange={handleChange}
                  >
                    <option value="ACTIVE">ACTIVE</option>
                    <option value="RETURNED">RETURNED</option>
                    <option value="OVERDUE">OVERDUE</option>
                  </select>
                </div>
                <div className="col-md-6 mb-3">
                  <label className="form-label">Штраф</label>
                  <input
                    type="number"
                    className="form-control"
                    name="fineAmount"
                    value={formData.fineAmount}
                    onChange={handleChange}
                    step="0.01"
                    min="0"
                  />
                </div>
              </div>
            )}
            <div className="d-flex gap-2 mt-3">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Сохранение...' : 'Сохранить'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/loans')}>
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default LoanForm;

// angular-frontend/src/app/components/loan-form/loan-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { LoanService } from '../../services/loan.service';
import { BookService } from '../../services/book.service';
import { UserService } from '../../services/user.service';
import { LoanCreateDTO, LoanUpdateDTO } from '../../models/loan.model';
import { Book } from '../../models/book.model';
import { User } from '../../models/user.model';

@Component({
  selector: 'app-loan-form',
  templateUrl: './loan-form.component.html',
  styleUrls: ['./loan-form.component.css']
})
export class LoanFormComponent implements OnInit {
  isEdit = false;
  id?: number;
  loading = false;
  error = '';
  books: Book[] = [];
  users: User[] = [];
  formData: LoanCreateDTO & LoanUpdateDTO = {
    bookId: 0,
    userId: 0,
    status: 'ACTIVE',
    fineAmount: 0
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private loanService: LoanService,
    private bookService: BookService,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
    this.isEdit = !!this.id;
    this.fetchBooksAndUsers();
    if (this.isEdit) {
      this.fetchLoan();
    }
  }

  fetchBooksAndUsers(): void {
    this.bookService.getAll({ page: 0, size: 100 }).subscribe({
      next: (response) => this.books = response.content,
      error: (err) => console.error(err)
    });
    this.userService.getAll({ page: 0, size: 100 }).subscribe({
      next: (response) => this.users = response.content,
      error: (err) => console.error(err)
    });
  }

  fetchLoan(): void {
    this.loading = true;
    this.loanService.getById(this.id!).subscribe({
      next: (loan) => {
        this.formData = {
          bookId: loan.bookId,
          userId: loan.userId,
          status: loan.status,
          fineAmount: loan.fineAmount
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки выдачи';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    const request = this.isEdit
      ? this.loanService.update(this.id!, this.formData)
      : this.loanService.create(this.formData as LoanCreateDTO);
    request.subscribe({
      next: () => {
        this.router.navigate(['/loans']);
      },
      error: (err) => {
        this.error = 'Ошибка сохранения';
        console.error(err);
        this.loading = false;
      }
    });
  }
}
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h3>{{ isEdit ? '✏️ Редактирование выдачи' : '➕ Новая выдача' }}</h3>
    </div>
    <div class="card-body">
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <form (ngSubmit)="onSubmit()">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Книга *</label>
            <select class="form-select" [(ngModel)]="formData.bookId" name="bookId" required [disabled]="isEdit">
              <option value="0">Выберите книгу</option>
              <option *ngFor="let book of books" [value]="book.id">{{ book.title }} (доступно: {{ book.availableCopies || 0 }})</option>
            </select>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Пользователь *</label>
            <select class="form-select" [(ngModel)]="formData.userId" name="userId" required [disabled]="isEdit">
              <option value="0">Выберите пользователя</option>
              <option *ngFor="let user of users" [value]="user.id">{{ user.fullName }} ({{ user.email }})</option>
            </select>
          </div>
        </div>

        <div *ngIf="isEdit" class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Статус</label>
            <select class="form-select" [(ngModel)]="formData.status" name="status">
              <option value="ACTIVE">ACTIVE</option>
              <option value="RETURNED">RETURNED</option>
              <option value="OVERDUE">OVERDUE</option>
            </select>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Штраф</label>
            <input type="number" class="form-control" [(ngModel)]="formData.fineAmount" name="fineAmount" step="0.01" min="0">
          </div>
        </div>

        <div class="d-flex gap-2 mt-3">
          <button type="submit" class="btn btn-primary" [disabled]="loading">{{ loading ? 'Сохранение...' : 'Сохранить' }}</button>
          <button type="button" class="btn btn-secondary" routerLink="/loans">Отмена</button>
        </div>
      </form>
    </div>
  </div>
</div>
