// angular-frontend/src/app/components/publisher-list/publisher-list.component.ts
import { Component, OnInit } from '@angular/core';
import { PublisherService } from '../../services/publisher.service';
import { Publisher } from '../../models/publisher.model';
import { PageResponse } from '../../models/pagination.model';

@Component({
  selector: 'app-publisher-list',
  templateUrl: './publisher-list.component.html',
  styleUrls: ['./publisher-list.component.css']
})
export class PublisherListComponent implements OnInit {
  publishers: Publisher[] = [];
  loading = true;
  error = '';
  page = 0;
  totalPages = 0;
  totalElements = 0;

  constructor(private publisherService: PublisherService) {}

  ngOnInit(): void {
    this.fetchPublishers();
  }

  fetchPublishers(): void {
    this.loading = true;
    this.publisherService.getAll({ page: this.page, size: 10 }).subscribe({
      next: (response: PageResponse<Publisher>) => {
        this.publishers = response.content;
        this.totalPages = response.totalPages;
        this.totalElements = response.totalElements;
        this.error = '';
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки данных';
        console.error(err);
        this.loading = false;
      }
    });
  }

  deletePublisher(id: number): void {
    if (confirm('Вы уверены, что хотите удалить этого издателя?')) {
      this.publisherService.delete(id).subscribe({
        next: () => this.fetchPublishers(),
        error: (err) => {
          this.error = 'Ошибка удаления';
          console.error(err);
        }
      });
    }
  }

  changePage(page: number): void {
    this.page = page;
    this.fetchPublishers();
  }

  getPageNumbers(): number[] {
    const pages: number[] = [];
    const total = Math.min(this.totalPages, 7);
    let start = 0;
    if (this.totalPages > 7) {
      if (this.page < 3) {
        start = 0;
      } else if (this.page > this.totalPages - 4) {
        start = this.totalPages - 7;
      } else {
        start = this.page - 3;
      }
    }
    for (let i = 0; i < total; i++) {
      pages.push(start + i);
    }
    return pages;
  }
}
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2>🏢 Управление издателями</h2>
    <div>
      <button class="btn btn-primary me-2" routerLink="/publishers/new">➕ Новый издатель</button>
      <span class="badge bg-primary">Всего: {{ totalElements }}</span>
    </div>
  </div>

  <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

  <div *ngIf="loading" class="text-center mt-5">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Загрузка...</span>
    </div>
  </div>

  <div class="table-responsive" *ngIf="!loading">
    <table class="table table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>ID</th>
          <th>Название</th>
          <th>Адрес</th>
          <th>Телефон</th>
          <th>Email</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngIf="publishers.length === 0">
          <td colspan="6" class="text-center text-muted py-3">Нет данных</td>
        </tr>
        <tr *ngFor="let publisher of publishers">
          <td>{{ publisher.id }}</td>
          <td>{{ publisher.name }}</td>
          <td>{{ publisher.address || '—' }}</td>
          <td>{{ publisher.phone || '—' }}</td>
          <td>{{ publisher.email || '—' }}</td>
          <td>
            <button class="btn btn-sm btn-info me-1" [routerLink]="['/publishers', publisher.id, 'edit']">✏️</button>
            <button class="btn btn-sm btn-danger" (click)="deletePublisher(publisher.id!)">🗑️</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <nav *ngIf="totalPages > 1" class="mt-3">
    <ul class="pagination justify-content-center">
      <li class="page-item" [class.disabled]="page === 0">
        <button class="page-link" (click)="changePage(page - 1)">Назад</button>
      </li>
      <li class="page-item" *ngFor="let pageNum of getPageNumbers()" [class.active]="page === pageNum">
        <button class="page-link" (click)="changePage(pageNum)">{{ pageNum + 1 }}</button>
      </li>
      <li class="page-item" [class.disabled]="page >= totalPages - 1">
        <button class="page-link" (click)="changePage(page + 1)">Вперед</button>
      </li>
    </ul>
  </nav>
</div>

// library-frontend/src/components/PublisherList/PublisherList.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { publisherService } from '../../services/publisherService';
import { Publisher } from '../../models/publisher.model';
import { PageResponse } from '../../models/pagination.model';

const PublisherList: React.FC = () => {
  const navigate = useNavigate();
  const [publishers, setPublishers] = useState<Publisher[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [totalElements, setTotalElements] = useState(0);

  useEffect(() => {
    fetchPublishers();
  }, [page]);

  const fetchPublishers = async () => {
    try {
      setLoading(true);
      const response: PageResponse<Publisher> = await publisherService.getAll({ page, size: 10 });
      setPublishers(response.content);
      setTotalPages(response.totalPages);
      setTotalElements(response.totalElements);
      setError('');
    } catch (err: any) {
      setError('Ошибка загрузки данных: ' + (err.message || ''));
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('Вы уверены, что хотите удалить этого издателя?')) {
      try {
        await publisherService.delete(id);
        fetchPublishers();
      } catch (err) {
        setError('Ошибка удаления');
        console.error(err);
      }
    }
  };

  if (loading) {
    return (
      <div className="d-flex justify-content-center mt-5">
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Загрузка...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="container mt-4">
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h2>🏢 Управление издателями</h2>
        <div>
          <button 
            className="btn btn-primary me-2"
            onClick={() => navigate('/publishers/new')}
          >
            ➕ Новый издатель
          </button>
          <span className="badge bg-primary">Всего: {totalElements}</span>
        </div>
      </div>

      {error && (
        <div className="alert alert-danger alert-dismissible fade show" role="alert">
          {error}
          <button type="button" className="btn-close" onClick={() => setError('')}></button>
        </div>
      )}

      <div className="table-responsive">
        <table className="table table-striped table-hover">
          <thead className="table-dark">
            <tr>
              <th>ID</th>
              <th>Название</th>
              <th>Адрес</th>
              <th>Телефон</th>
              <th>Email</th>
              <th>Действия</th>
            </tr>
          </thead>
          <tbody>
            {publishers.length === 0 ? (
              <tr>
                <td colSpan={6} className="text-center text-muted py-3">Нет данных</td>
              </tr>
            ) : (
              publishers.map((publisher) => (
                <tr key={publisher.id}>
                  <td>{publisher.id}</td>
                  <td>{publisher.name}</td>
                  <td>{publisher.address || '—'}</td>
                  <td>{publisher.phone || '—'}</td>
                  <td>{publisher.email || '—'}</td>
                  <td>
                    <button
                      className="btn btn-sm btn-info me-1"
                      onClick={() => navigate(`/publishers/${publisher.id}/edit`)}
                      title="Редактировать"
                    >
                      ✏️
                    </button>
                    <button
                      className="btn btn-sm btn-danger"
                      onClick={() => handleDelete(publisher.id!)}
                      title="Удалить издателя"
                    >
                      🗑️
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {totalPages > 1 && (
        <nav className="mt-3">
          <ul className="pagination justify-content-center">
            <li className={`page-item ${page === 0 ? 'disabled' : ''}`}>
              <button className="page-link" onClick={() => setPage(page - 1)}>
                Назад
              </button>
            </li>
            {[...Array(Math.min(totalPages, 7))].map((_, i) => {
              let pageNum = i;
              if (totalPages > 7) {
                if (page < 3) pageNum = i;
                else if (page > totalPages - 4) pageNum = totalPages - 7 + i;
                else pageNum = page - 3 + i;
              }
              return (
                <li key={pageNum} className={`page-item ${page === pageNum ? 'active' : ''}`}>
                  <button className="page-link" onClick={() => setPage(pageNum)}>
                    {pageNum + 1}
                  </button>
                </li>
              );
            })}
            <li className={`page-item ${page >= totalPages - 1 ? 'disabled' : ''}`}>
              <button className="page-link" onClick={() => setPage(page + 1)}>
                Вперед
              </button>
            </li>
          </ul>
        </nav>
      )}
    </div>
  );
};

export default PublisherList;
