// angular-frontend/src/app/components/book-form/book-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { BookService } from '../../services/book.service';
import { AuthorService } from '../../services/author.service';
import { GenreService } from '../../services/genre.service';
import { PublisherService } from '../../services/publisher.service';
import { BookCreateDTO, BookUpdateDTO } from '../../models/book.model';
import { Author } from '../../models/author.model';
import { Genre } from '../../models/genre.model';
import { Publisher } from '../../models/publisher.model';

@Component({
  selector: 'app-book-form',
  templateUrl: './book-form.component.html',
  styleUrls: ['./book-form.component.css']
})
export class BookFormComponent implements OnInit {
  isEdit = false;
  id?: number;
  loading = false;
  error = '';
  authors: Author[] = [];
  genres: Genre[] = [];
  publishers: Publisher[] = [];

  formData: BookCreateDTO & BookUpdateDTO = {
    title: '',
    isbn: '',
    publicationYear: new Date().getFullYear(),
    publisherId: 0,
    totalCopies: 1,
    pageCount: 0,
    description: '',
    authors: [],
    genres: []
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private bookService: BookService,
    private authorService: AuthorService,
    private genreService: GenreService,
    private publisherService: PublisherService
  ) {}

  ngOnInit(): void {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
    this.isEdit = !!this.id;
    this.fetchData();
    if (this.isEdit) {
      this.fetchBook();
    }
  }

  fetchData(): void {
    this.authorService.getAll({ page: 0, size: 100 }).subscribe({
      next: (response) => this.authors = response.content,
      error: (err) => console.error(err)
    });
    this.genreService.getAll({ page: 0, size: 100 }).subscribe({
      next: (response) => this.genres = response.content,
      error: (err) => console.error(err)
    });
    this.publisherService.getAll({ page: 0, size: 100 }).subscribe({
      next: (response) => this.publishers = response.content,
      error: (err) => console.error(err)
    });
  }

  fetchBook(): void {
    this.loading = true;
    this.bookService.getById(this.id!).subscribe({
      next: (book) => {
        this.formData = {
          title: book.title,
          isbn: book.isbn,
          publicationYear: book.publicationYear,
          publisherId: book.publisherId,
          totalCopies: book.totalCopies,
          pageCount: book.pageCount,
          description: book.description,
          authors: book.authors.map(a => ({ id: a.id! })),
          genres: book.genres.map(g => ({ id: g.id! }))
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Ошибка загрузки книги';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    const request = this.isEdit
      ? this.bookService.update(this.id!, this.formData)
      : this.bookService.create(this.formData as BookCreateDTO);
    request.subscribe({
      next: () => {
        this.router.navigate(['/books']);
      },
      error: (err) => {
        this.error = 'Ошибка сохранения';
        console.error(err);
        this.loading = false;
      }
    });
  }

  onAuthorSelect(event: Event): void {
    const select = event.target as HTMLSelectElement;
    const selectedOptions = Array.from(select.selectedOptions);
    this.formData.authors = selectedOptions.map(opt => ({ id: Number(opt.value) }));
  }

  onGenreSelect(event: Event): void {
    const select = event.target as HTMLSelectElement;
    const selectedOptions = Array.from(select.selectedOptions);
    this.formData.genres = selectedOptions.map(opt => ({ id: Number(opt.value) }));
  }

  isAuthorSelected(authorId: number | undefined): boolean {
    if (authorId === undefined) return false;
    return this.formData.authors.some(a => a.id === authorId);
  }

  isGenreSelected(genreId: number | undefined): boolean {
    if (genreId === undefined) return false;
    return this.formData.genres.some(g => g.id === genreId);
  }
}
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      <h3>{{ isEdit ? '✏️ Редактирование книги' : '➕ Новая книга' }}</h3>
    </div>
    <div class="card-body">
      <div *ngIf="error" class="alert alert-danger">{{ error }}</div>

      <form (ngSubmit)="onSubmit()">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Название *</label>
            <input type="text" class="form-control" [(ngModel)]="formData.title" name="title" required>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">ISBN</label>
            <input type="text" class="form-control" [(ngModel)]="formData.isbn" name="isbn">
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 mb-3">
            <label class="form-label">Год публикации</label>
            <input type="number" class="form-control" [(ngModel)]="formData.publicationYear" name="publicationYear">
          </div>
          <div class="col-md-4 mb-3">
            <label class="form-label">Количество экземпляров</label>
            <input type="number" class="form-control" [(ngModel)]="formData.totalCopies" name="totalCopies" min="1">
          </div>
          <div class="col-md-4 mb-3">
            <label class="form-label">Количество страниц</label>
            <input type="number" class="form-control" [(ngModel)]="formData.pageCount" name="pageCount" min="0">
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Издатель</label>
          <select class="form-select" [(ngModel)]="formData.publisherId" name="publisherId">
            <option value="0">Выберите издателя</option>
            <option *ngFor="let publisher of publishers" [value]="publisher.id">{{ publisher.name }}</option>
          </select>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label class="form-label">Авторы</label>
            <select class="form-select" multiple (change)="onAuthorSelect($event)" name="authors">
              <option *ngFor="let author of authors" [value]="author.id" [selected]="isAuthorSelected(author.id)">{{ author.fullName }}</option>
            </select>
            <small class="text-muted">Держите Ctrl для выбора нескольких</small>
          </div>
          <div class="col-md-6 mb-3">
            <label class="form-label">Жанры</label>
            <select class="form-select" multiple (change)="onGenreSelect($event)" name="genres">
              <option *ngFor="let genre of genres" [value]="genre.id" [selected]="isGenreSelected(genre.id)">{{ genre.name }}</option>
            </select>
            <small class="text-muted">Держите Ctrl для выбора нескольких</small>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">Описание</label>
          <textarea class="form-control" [(ngModel)]="formData.description" name="description" rows="3"></textarea>
        </div>

        <div class="d-flex gap-2 mt-3">
          <button type="submit" class="btn btn-primary" [disabled]="loading">{{ loading ? 'Сохранение...' : 'Сохранить' }}</button>
          <button type="button" class="btn btn-secondary" routerLink="/books">Отмена</button>
        </div>
      </form>
    </div>
  </div>
</div>

// library-frontend/src/components/BookForm/BookForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { bookService } from '../../services/bookService';
import { authorService } from '../../services/authorService';
import { genreService } from '../../services/genreService';
import { publisherService } from '../../services/publisherService';

interface BookFormData {
  title: string;
  isbn: string;
  publicationYear: number;
  publisherId: number;
  totalCopies: number;
  pageCount: number;
  description: string;
  authors: { id: number }[];
  genres: { id: number }[];
}

const BookForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [authors, setAuthors] = useState<any[]>([]);
  const [genres, setGenres] = useState<any[]>([]);
  const [publishers, setPublishers] = useState<any[]>([]);

  const [formData, setFormData] = useState<BookFormData>({
    title: '',
    isbn: '',
    publicationYear: new Date().getFullYear(),
    publisherId: 0,
    totalCopies: 1,
    pageCount: 0,
    description: '',
    authors: [],
    genres: []
  });

  useEffect(() => {
    fetchData();
    if (isEdit) {
      fetchBook();
    }
  }, [id]);

  const fetchData = async () => {
    try {
      const [authorsRes, genresRes, publishersRes] = await Promise.all([
        authorService.getAll({ page: 0, size: 100 }),
        genreService.getAll({ page: 0, size: 100 }),
        publisherService.getAll({ page: 0, size: 100 })
      ]);
      setAuthors(authorsRes.content);
      setGenres(genresRes.content);
      setPublishers(publishersRes.content);
    } catch (err) {
      setError('Ошибка загрузки данных');
      console.error(err);
    }
  };

  const fetchBook = async () => {
    try {
      setLoading(true);
      const book = await bookService.getById(Number(id));
      setFormData({
        title: book.title,
        isbn: book.isbn,
        publicationYear: book.publicationYear,
        publisherId: book.publisherId,
        totalCopies: book.totalCopies,
        pageCount: book.pageCount,
        description: book.description,
        authors: book.authors.map((a: any) => ({ id: a.id! })),
        genres: book.genres.map((g: any) => ({ id: g.id! }))
      });
    } catch (err) {
      setError('Ошибка загрузки книги');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setLoading(true);
      if (isEdit) {
        await bookService.update(Number(id), formData);
      } else {
        await bookService.create(formData);
      }
      navigate('/books');
    } catch (err) {
      setError('Ошибка сохранения');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev: BookFormData) => ({
      ...prev,
      [name]: name === 'publicationYear' || name === 'publisherId' || name === 'totalCopies' || name === 'pageCount'
        ? Number(value)
        : value
    }));
  };

  const handleMultiSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const { name, options } = e.target;
    const selected = Array.from(options)
      .filter(option => option.selected)
      .map(option => ({ id: Number(option.value) }));
    setFormData((prev: BookFormData) => ({
      ...prev,
      [name]: selected
    }));
  };

  if (loading && isEdit) {
    return <div className="text-center mt-5"><div className="spinner-border"></div></div>;
  }

  return (
    <div className="container mt-4">
      <div className="card">
        <div className="card-header">
          <h3>{isEdit ? '✏️ Редактирование книги' : '➕ Новая книга'}</h3>
        </div>
        <div className="card-body">
          {error && <div className="alert alert-danger">{error}</div>}
          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Название *</label>
                <input
                  type="text"
                  className="form-control"
                  name="title"
                  value={formData.title}
                  onChange={handleChange}
                  required
                />
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">ISBN</label>
                <input
                  type="text"
                  className="form-control"
                  name="isbn"
                  value={formData.isbn}
                  onChange={handleChange}
                />
              </div>
            </div>
            <div className="row">
              <div className="col-md-4 mb-3">
                <label className="form-label">Год публикации</label>
                <input
                  type="number"
                  className="form-control"
                  name="publicationYear"
                  value={formData.publicationYear}
                  onChange={handleChange}
                />
              </div>
              <div className="col-md-4 mb-3">
                <label className="form-label">Количество экземпляров</label>
                <input
                  type="number"
                  className="form-control"
                  name="totalCopies"
                  value={formData.totalCopies}
                  onChange={handleChange}
                  min="1"
                />
              </div>
              <div className="col-md-4 mb-3">
                <label className="form-label">Количество страниц</label>
                <input
                  type="number"
                  className="form-control"
                  name="pageCount"
                  value={formData.pageCount}
                  onChange={handleChange}
                  min="0"
                />
              </div>
            </div>
            <div className="mb-3">
              <label className="form-label">Издатель</label>
              <select
                className="form-select"
                name="publisherId"
                value={formData.publisherId}
                onChange={handleChange}
              >
                <option value={0}>Выберите издателя</option>
                {publishers.map((publisher: any) => (
                  <option key={publisher.id} value={publisher.id}>
                    {publisher.name}
                  </option>
                ))}
              </select>
            </div>
            <div className="row">
              <div className="col-md-6 mb-3">
                <label className="form-label">Авторы</label>
                <select
                  className="form-select"
                  name="authors"
                  multiple
                  value={formData.authors.map((a: any) => String(a.id))}
                  onChange={handleMultiSelect}
                >
                  {authors.map((author: any) => (
                    <option key={author.id} value={author.id}>
                      {author.fullName}
                    </option>
                  ))}
                </select>
                <small className="text-muted">Держите Ctrl для выбора нескольких</small>
              </div>
              <div className="col-md-6 mb-3">
                <label className="form-label">Жанры</label>
                <select
                  className="form-select"
                  name="genres"
                  multiple
                  value={formData.genres.map((g: any) => String(g.id))}
                  onChange={handleMultiSelect}
                >
                  {genres.map((genre: any) => (
                    <option key={genre.id} value={genre.id}>
                      {genre.name}
                    </option>
                  ))}
                </select>
                <small className="text-muted">Держите Ctrl для выбора нескольких</small>
              </div>
            </div>
            <div className="mb-3">
              <label className="form-label">Описание</label>
              <textarea
                className="form-control"
                name="description"
                value={formData.description}
                onChange={handleChange}
                rows={3}
              />
            </div>
            <div className="d-flex gap-2 mt-3">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? 'Сохранение...' : 'Сохранить'}
              </button>
              <button type="button" className="btn btn-secondary" onClick={() => navigate('/books')}>
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default BookForm;
